// GENERATED — do not edit by hand.
// Source: @basementstudio/shader-lab 1.5.0 (src/lib/editor/config/layer-registry.ts)
// Regenerate: node tools/gen_shader_lab_schema.mjs <shader-lab-checkout> <version>
//
// The shipped parameter registry for every published layer type: the same
// defaults, ranges, enums and visibility rules the shader-lab editor itself
// uses. shader_lab_panel.js builds its controls from this, so the panel cannot
// drift from the library the way a hand-maintained table does.

export const SHADER_LAB_VERSION = "1.5.0";

export const SOURCE_TYPES = ["custom-shader","fluid","gradient","image","live","magnify-lens","pixel-trail","text","video"];

export const EFFECT_TYPES = ["ascii","blob-tracking","bloom","chromatic-aberration","circuit-bent","crt","directional-blur","displacement-map","dithering","edge-detect","fluted-glass","halftone","ink","particle-grid","pattern","pixel-sorting","pixelation","plotter","posterize","slice","smear","threshold","voxel"];

export const LAYER_SCHEMA = {
    "ascii": {
        kind: "effect",
        defaultName: "ASCII",
        params: [
        {"key":"cellSize","type":"number","defaultValue":12,"min":4,"max":48,"step":1},
        {"key":"charset","type":"select","defaultValue":"light","options":["light","dense","blocks","hatching","binary","custom"]},
        {"key":"customChars","type":"text","defaultValue":" .:-=+*#%@","visibleWhen":{"key":"charset","equals":"custom"}},
        {"key":"fontWeight","type":"select","defaultValue":"regular","options":["thin","regular","bold"]},
        {"key":"colorMode","type":"select","defaultValue":"monochrome","options":["source","monochrome"]},
        {"key":"monoColor","type":"color","defaultValue":"#f5f5f0","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"bgOpacity","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"source"}},
        {"key":"invert","type":"boolean","defaultValue":false},
        {"key":"toneMapping","type":"select","defaultValue":"none","options":["none","aces","reinhard","totos","cinematic"]},
        {"key":"glyphSignalMode","type":"select","defaultValue":"luminance","options":["luminance","lightness","red","green","blue"]},
        {"key":"colorSignalMode","type":"select","defaultValue":"luminance","options":["luminance","lightness","red","green","blue"]},
        {"key":"signalBlackPoint","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"signalWhitePoint","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        {"key":"signalGamma","type":"number","defaultValue":1,"min":0.1,"max":5,"step":0.01},
        {"key":"presenceThreshold","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"presenceSoftness","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"shimmerAmount","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"shimmerSpeed","type":"number","defaultValue":1,"min":0,"max":10,"step":0.1},
        {"key":"directionBias","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"bloomEnabled","type":"boolean","defaultValue":false},
        {"key":"bloomIntensity","type":"number","defaultValue":1.25,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":6,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        ],
    },
    "blob-tracking": {
        kind: "effect",
        defaultName: "Blob Tracking",
        params: [
        {"key":"detectionMode","type":"select","defaultValue":"auto","options":["auto","motion","luminance"]},
        {"key":"sensitivity","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        {"key":"motionThreshold","type":"number","defaultValue":0.12,"min":0,"max":1,"step":0.01},
        {"key":"blobAmount","type":"number","defaultValue":6,"min":1,"max":32,"step":1},
        {"key":"minBlobSize","type":"number","defaultValue":3,"min":1,"max":64,"step":1},
        {"key":"smoothing","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01},
        {"key":"persistentTracking","type":"boolean","defaultValue":true},
        {"key":"shapeType","type":"select","defaultValue":"square","options":["square","circle","diamond"]},
        {"key":"shapeScale","type":"number","defaultValue":1,"min":0.25,"max":3,"step":0.01},
        {"key":"invert","type":"boolean","defaultValue":false},
        {"key":"outputMode","type":"select","defaultValue":"decorated","options":["decorated","mask"]},
        {"key":"innerEffectType","type":"select","defaultValue":"none","options":["none","ascii","bloom","circuit-bent","directional-blur","fluted-glass","ink","pattern","plotter","posterize","threshold","crt","dithering","halftone","particle-grid","pixelation","pixel-sorting","slice","smear","edge-detect","displacement-map","chromatic-aberration","voxel"]},
        {"key":"innerEffectParams","type":"text","defaultValue":"","visibleWhen":{"key":"__blobTrackingInternal","equals":"__never__"}},
        {"key":"showOutline","type":"boolean","defaultValue":true},
        {"key":"strokeWidth","type":"number","defaultValue":2,"min":1,"max":8,"step":1},
        {"key":"strokeColor","type":"color","defaultValue":"#ffffff"},
        {"key":"showLabels","type":"boolean","defaultValue":true},
        {"key":"centerShape","type":"select","defaultValue":"dot","options":["dot","cross","none"]},
        {"key":"connectLines","type":"boolean","defaultValue":true},
        {"key":"curvedLines","type":"boolean","defaultValue":false,"visibleWhen":{"key":"connectLines","equals":true}},
        {"key":"connectorDashed","type":"boolean","defaultValue":false,"visibleWhen":{"key":"connectLines","equals":true}},
        {"key":"connectorArrows","type":"boolean","defaultValue":false,"visibleWhen":{"key":"connectLines","equals":true}},
        {"key":"trailDecay","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01},
        ],
    },
    "bloom": {
        kind: "effect",
        defaultName: "Bloom",
        params: [
        {"key":"bloomIntensity","type":"number","defaultValue":1.25,"min":0,"max":8,"step":0.01},
        {"key":"bloomThreshold","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01},
        {"key":"bloomRadius","type":"number","defaultValue":6,"min":0,"max":24,"step":0.25},
        {"key":"bloomSoftness","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01},
        {"key":"bloomKnee","type":"number","defaultValue":0.2,"min":0,"max":0.5,"step":0.01},
        {"key":"highlightDrive","type":"number","defaultValue":1.5,"min":1,"max":4,"step":0.01},
        ],
    },
    "chromatic-aberration": {
        kind: "effect",
        defaultName: "Chromatic Aberration",
        params: [
        {"key":"intensity","type":"number","defaultValue":5,"min":0,"max":50,"step":0.5},
        {"key":"direction","type":"select","defaultValue":"radial","options":["radial","horizontal","vertical"]},
        {"key":"center","type":"vec2","defaultValue":[0.5,0.5],"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"direction","equals":"radial"}},
        {"key":"angle","type":"number","defaultValue":0,"min":0,"max":360,"step":1,"visibleWhen":{"key":"direction","equals":"horizontal"}},
        ],
    },
    "circuit-bent": {
        kind: "effect",
        defaultName: "Circuit Bent",
        params: [
        {"key":"colorMode","type":"select","defaultValue":"source","options":["source","monochrome"]},
        {"key":"monoColor","type":"color","defaultValue":"#ebf5ff","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"invert","type":"boolean","defaultValue":false},
        {"key":"signalBlackPoint","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"signalWhitePoint","type":"number","defaultValue":0.22,"min":0,"max":1,"step":0.01},
        {"key":"signalGamma","type":"number","defaultValue":3.07,"min":0.1,"max":5,"step":0.01},
        {"key":"presenceThreshold","type":"number","defaultValue":0.37,"min":0,"max":1,"step":0.01},
        {"key":"presenceSoftness","type":"number","defaultValue":0.64,"min":0,"max":1,"step":0.01},
        {"key":"linePitch","type":"number","defaultValue":6.4,"min":2,"max":48,"step":0.1},
        {"key":"lineThickness","type":"number","defaultValue":0.5,"min":0.5,"max":8,"step":0.1},
        {"key":"lineAngle","type":"number","defaultValue":0,"min":0,"max":180,"step":1},
        {"key":"noiseMode","type":"select","defaultValue":"turbulence","options":["sine","perlin","turbulence"]},
        {"key":"noiseAmount","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        {"key":"scrollSpeed","type":"number","defaultValue":4,"min":0,"max":4,"step":0.01},
        ],
    },
    "crt": {
        kind: "effect",
        defaultName: "CRT",
        params: [
        {"key":"crtMode","type":"select","defaultValue":"slot-mask","options":["slot-mask","aperture-grille","composite-tv"]},
        {"key":"cellSize","type":"number","defaultValue":3,"min":3,"max":32,"step":1},
        {"key":"scanlineIntensity","type":"number","defaultValue":0.17,"min":0,"max":1,"step":0.01},
        {"key":"maskIntensity","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        {"key":"barrelDistortion","type":"number","defaultValue":0.15,"min":0,"max":0.3,"step":0.001},
        {"key":"chromaticAberration","type":"number","defaultValue":2,"min":0,"max":2,"step":0.01},
        {"key":"beamFocus","type":"number","defaultValue":0.58,"min":0,"max":1,"step":0.01},
        {"key":"brightness","type":"number","defaultValue":1.2,"min":0.5,"max":100,"step":0.01},
        {"key":"highlightDrive","type":"number","defaultValue":1,"min":1,"max":100,"step":0.01},
        {"key":"highlightThreshold","type":"number","defaultValue":0.62,"min":0,"max":1,"step":0.01},
        {"key":"shoulder","type":"number","defaultValue":0.25,"min":0,"max":4,"step":0.01},
        {"key":"chromaRetention","type":"number","defaultValue":1.15,"min":0,"max":2,"step":0.01},
        {"key":"shadowLift","type":"number","defaultValue":0.16,"min":0,"max":1,"step":0.01},
        {"key":"persistence","type":"number","defaultValue":0.18,"min":0,"max":1,"step":0.01},
        {"key":"vignetteIntensity","type":"number","defaultValue":0.45,"min":0,"max":1,"step":0.01},
        {"key":"flickerIntensity","type":"number","defaultValue":0.2,"min":0,"max":0.2,"step":0.01},
        {"key":"glitchIntensity","type":"number","defaultValue":0.13,"min":0,"max":1,"step":0.01},
        {"key":"glitchSpeed","type":"number","defaultValue":5,"min":0.1,"max":5,"step":0.1,"visibleWhen":{"key":"glitchIntensity"}},
        {"key":"signalArtifacts","type":"number","defaultValue":0.45,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"crtMode","equals":"composite-tv"}},
        {"key":"bloomEnabled","type":"boolean","defaultValue":true},
        {"key":"bloomIntensity","type":"number","defaultValue":1.93,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":8,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.31,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        ],
    },
    "custom-shader": {
        kind: "source",
        defaultName: "Custom Shader",
        params: [
        {"key":"effectMode","type":"boolean","defaultValue":false,"visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        {"key":"sourceMode","type":"select","defaultValue":"paste","options":["paste","file"],"visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        {"key":"sourceCode","type":"text","defaultValue":"export const sketch = Fn(() => {\n  const uv0 = screenAspectUV(screenSize)\n  const color = vec3(\n    uv0.x.add(0.5),\n    uv0.y.add(0.5),\n    sin(time).mul(0.5).add(0.5)\n  ).toVar()\n\n  color.assign(technicolorTonemap(color))\n\n  return color\n})\n","visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        {"key":"sourceFileName","type":"text","defaultValue":"","visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        {"key":"entryExport","type":"text","defaultValue":"sketch","visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        {"key":"sourceRevision","type":"number","defaultValue":0,"min":0,"max":9007199254740991,"step":1,"visibleWhen":{"key":"__customShaderInternal","equals":"__never__"}},
        ],
    },
    "directional-blur": {
        kind: "effect",
        defaultName: "Directional Blur",
        params: [
        {"key":"mode","type":"select","defaultValue":"linear","options":["linear","radial"]},
        {"key":"strength","type":"number","defaultValue":18,"min":0,"max":96,"step":0.5},
        {"key":"samples","type":"number","defaultValue":8,"min":1,"max":16,"step":1},
        {"key":"angle","type":"number","defaultValue":0,"min":0,"max":360,"step":1,"visibleWhen":{"key":"mode","equals":"linear"}},
        {"key":"center","type":"vec2","defaultValue":[0.5,0.5],"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"mode","equals":"radial"}},
        ],
    },
    "displacement-map": {
        kind: "effect",
        defaultName: "Displacement Map",
        params: [
        {"key":"strength","type":"number","defaultValue":20,"min":0,"max":200,"step":1},
        {"key":"direction","type":"select","defaultValue":"both","options":["both","horizontal","vertical"]},
        {"key":"channel","type":"select","defaultValue":"luminance","options":["luminance","red","green","blue"]},
        {"key":"midpoint","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        ],
    },
    "dithering": {
        kind: "effect",
        defaultName: "Dithering",
        params: [
        {"key":"preset","type":"select","defaultValue":"custom","options":["custom","gameboy"]},
        {"key":"algorithm","type":"select","defaultValue":"bayer-4x4","options":["bayer-2x2","bayer-4x4","bayer-8x8","noise"]},
        {"key":"colorMode","type":"select","defaultValue":"source","options":["monochrome","source","duo-tone"]},
        {"key":"monoColor","type":"color","defaultValue":"#f5f5f0","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"shadowColor","type":"color","defaultValue":"#101010","visibleWhen":{"key":"colorMode","equals":"duo-tone"}},
        {"key":"highlightColor","type":"color","defaultValue":"#f5f2e8","visibleWhen":{"key":"colorMode","equals":"duo-tone"}},
        {"key":"pixelSize","type":"number","defaultValue":1,"min":1,"max":24,"step":1},
        {"key":"spread","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        {"key":"levels","type":"number","defaultValue":4,"min":2,"max":16,"step":1},
        {"key":"dotScale","type":"number","defaultValue":1,"min":0.1,"max":1,"step":0.1},
        {"key":"animateDither","type":"boolean","defaultValue":false},
        {"key":"ditherSpeed","type":"number","defaultValue":1,"min":0,"max":3,"step":0.5,"visibleWhen":{"key":"animateDither","equals":true}},
        {"key":"chromaticSplit","type":"boolean","defaultValue":false},
        ],
    },
    "edge-detect": {
        kind: "effect",
        defaultName: "Edge Detect",
        params: [
        {"key":"threshold","type":"number","defaultValue":0.1,"min":0,"max":1,"step":0.01},
        {"key":"strength","type":"number","defaultValue":1,"min":0.1,"max":5,"step":0.1},
        {"key":"invert","type":"boolean","defaultValue":false},
        {"key":"colorMode","type":"select","defaultValue":"overlay","options":["overlay","mono","source"]},
        {"key":"lineColor","type":"color","defaultValue":"#ffffff","visibleWhen":{"key":"colorMode","equals":"mono"}},
        {"key":"bgColor","type":"color","defaultValue":"#000000","visibleWhen":{"key":"colorMode","equals":"mono"}},
        ],
    },
    "fluid": {
        kind: "source",
        defaultName: "Fluid",
        params: [
        {"key":"simRes","type":"number","defaultValue":192,"min":32,"max":512,"step":32},
        {"key":"dyeRes","type":"number","defaultValue":1024,"min":128,"max":2048,"step":64},
        {"key":"iterations","type":"number","defaultValue":20,"min":1,"max":32,"step":1},
        {"key":"densityDissipation","type":"number","defaultValue":4,"min":0,"max":8,"step":0.01},
        {"key":"velocityDissipation","type":"number","defaultValue":0.2,"min":0,"max":4,"step":0.01},
        {"key":"pressureDissipation","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"curlStrength","type":"number","defaultValue":30,"min":0,"max":80,"step":1},
        {"key":"radius","type":"number","defaultValue":1,"min":0.05,"max":2,"step":0.01},
        {"key":"splatForce","type":"number","defaultValue":6000,"min":500,"max":15000,"step":100},
        {"key":"autoSplats","type":"boolean","defaultValue":true},
        {"key":"brightness","type":"number","defaultValue":1.6,"min":0.1,"max":4,"step":0.01},
        {"key":"colorMode","type":"select","defaultValue":"monochrome","options":["monochrome","duotone","source"]},
        {"key":"monoDark","type":"color","defaultValue":"#000000","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"monoLight","type":"color","defaultValue":"#ffffff","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"duotoneDark","type":"color","defaultValue":"#101010","visibleWhen":{"key":"colorMode","equals":"duotone"}},
        {"key":"duotoneLight","type":"color","defaultValue":"#f3f3ef","visibleWhen":{"key":"colorMode","equals":"duotone"}},
        ],
    },
    "fluted-glass": {
        kind: "effect",
        defaultName: "Fluted Glass",
        params: [
        {"key":"preset","type":"select","defaultValue":"architectural","options":["architectural","painterly"]},
        {"key":"frequency","type":"number","defaultValue":20,"min":2,"max":100,"step":1},
        {"key":"amplitude","type":"number","defaultValue":0.02,"min":0,"max":0.1,"step":0.001},
        {"key":"warp","type":"number","defaultValue":0.28,"min":0,"max":1,"step":0.01},
        {"key":"irregularity","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01},
        {"key":"angle","type":"number","defaultValue":0,"min":0,"max":360,"step":1},
        ],
    },
    "gradient": {
        kind: "source",
        defaultName: "Gradient",
        params: [
        {"key":"preset","type":"select","defaultValue":"custom","options":["custom","aurora","sunset","deep-ocean","neon-glow"]},
        {"key":"activePoints","type":"number","defaultValue":3,"min":2,"max":5,"step":1},
        {"key":"point1Color","type":"color","defaultValue":"#0E0C0C"},
        {"key":"point1Position","type":"vec2","defaultValue":[-0.82,-0.62],"min":-1.5,"max":1.5,"step":0.01},
        {"key":"point1Weight","type":"number","defaultValue":0.42,"min":0,"max":3,"step":0.01},
        {"key":"point2Color","type":"color","defaultValue":"#C1FF00"},
        {"key":"point2Position","type":"vec2","defaultValue":[0.22,0.72],"min":-1.5,"max":1.5,"step":0.01},
        {"key":"point2Weight","type":"number","defaultValue":1.55,"min":0,"max":3,"step":0.01},
        {"key":"point3Color","type":"color","defaultValue":"#B2DAD5","visibleWhen":{"key":"activePoints"}},
        {"key":"point3Position","type":"vec2","defaultValue":[0.88,-0.26],"min":-1.5,"max":1.5,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"point3Weight","type":"number","defaultValue":0.64,"min":0,"max":3,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"point4Color","type":"color","defaultValue":"#3B4148","visibleWhen":{"key":"activePoints"}},
        {"key":"point4Position","type":"vec2","defaultValue":[-0.34,0.52],"min":-1.5,"max":1.5,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"point4Weight","type":"number","defaultValue":0.82,"min":0,"max":3,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"point5Color","type":"color","defaultValue":"#F3E7D0","visibleWhen":{"key":"activePoints"}},
        {"key":"point5Position","type":"vec2","defaultValue":[0.58,-0.76],"min":-1.5,"max":1.5,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"point5Weight","type":"number","defaultValue":0.48,"min":0,"max":3,"step":0.01,"visibleWhen":{"key":"activePoints"}},
        {"key":"noiseType","type":"select","defaultValue":"ridge","options":["simplex","perlin","value","voronoi","ridge","turbulence"]},
        {"key":"noiseSeed","type":"number","defaultValue":70.3,"min":0,"max":100,"step":0.1},
        {"key":"warpAmount","type":"number","defaultValue":0.18,"min":0,"max":1,"step":0.01},
        {"key":"warpScale","type":"number","defaultValue":2.35,"min":0.1,"max":6,"step":0.01},
        {"key":"warpIterations","type":"number","defaultValue":1,"min":1,"max":5,"step":1},
        {"key":"warpDecay","type":"number","defaultValue":1,"min":0.1,"max":3,"step":0.01},
        {"key":"warpBias","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        {"key":"vortexAmount","type":"number","defaultValue":0.69,"min":-1,"max":1,"step":0.01},
        {"key":"animate","type":"boolean","defaultValue":true},
        {"key":"motionAmount","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        {"key":"motionSpeed","type":"number","defaultValue":0.4,"min":0,"max":2,"step":0.01,"visibleWhen":{"key":"animate","equals":true}},
        {"key":"falloff","type":"number","defaultValue":2.05,"min":0.5,"max":4,"step":0.01},
        {"key":"tonemapMode","type":"select","defaultValue":"cinematic","options":["none","aces","reinhard","totos","cinematic"]},
        {"key":"glowStrength","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"glowThreshold","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"grainAmount","type":"number","defaultValue":0.08,"min":0,"max":1,"step":0.01},
        {"key":"vignetteStrength","type":"number","defaultValue":0.12,"min":0,"max":1,"step":0.01},
        {"key":"vignetteRadius","type":"number","defaultValue":1.5,"min":0,"max":1.5,"step":0.01},
        {"key":"vignetteSoftness","type":"number","defaultValue":1,"min":0.01,"max":1,"step":0.01},
        ],
    },
    "halftone": {
        kind: "effect",
        defaultName: "Halftone",
        params: [
        {"key":"colorMode","type":"select","defaultValue":"cmyk","options":["source","monochrome","duotone","custom","cmyk"]},
        {"key":"shape","type":"select","defaultValue":"circle","options":["circle","square","diamond","line"]},
        {"key":"spacing","type":"number","defaultValue":5,"min":2,"max":48,"step":1},
        {"key":"dotSize","type":"number","defaultValue":1,"min":0.1,"max":3,"step":0.01},
        {"key":"dotMin","type":"number","defaultValue":0,"min":0,"max":0.5,"step":0.01},
        {"key":"angle","type":"number","defaultValue":28,"min":0,"max":360,"step":1},
        {"key":"contrast","type":"number","defaultValue":1,"min":0,"max":2,"step":0.01},
        {"key":"softness","type":"number","defaultValue":0.25,"min":0,"max":1,"step":0.01},
        {"key":"dotGain","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"dotMorph","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"invertLuma","type":"boolean","defaultValue":false},
        {"key":"customColorCount","type":"number","defaultValue":4,"min":2,"max":4,"step":1,"visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customLuminanceBias","type":"number","defaultValue":0,"min":-1,"max":1,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"bloomEnabled","type":"boolean","defaultValue":false,"visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"bloomIntensity","type":"number","defaultValue":1.25,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":6,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"customBgColor","type":"color","defaultValue":"#F5F5F0","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor1","type":"color","defaultValue":"#0d1014","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor2","type":"color","defaultValue":"#4d5057","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor3","type":"color","defaultValue":"#969aa2","visibleWhen":{"key":"customColorCount"}},
        {"key":"customColor4","type":"color","defaultValue":"#e1e2de","visibleWhen":{"key":"customColorCount"}},
        {"key":"ink","type":"color","defaultValue":"#0d1014","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"duotoneLight","type":"color","defaultValue":"#F5F5F0","visibleWhen":{"key":"colorMode","equals":"duotone"}},
        {"key":"duotoneDark","type":"color","defaultValue":"#1d1d1c","visibleWhen":{"key":"colorMode","equals":"duotone"}},
        {"key":"preset","type":"select","defaultValue":"process","options":["process","risograph","newspaper","vintage","custom"],"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"gcr","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"cmykBlend","type":"select","defaultValue":"subtractive","options":["subtractive","overprint"],"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"cyanAngle","type":"number","defaultValue":15,"min":0,"max":90,"step":1,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"magentaAngle","type":"number","defaultValue":75,"min":0,"max":90,"step":1,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"yellowAngle","type":"number","defaultValue":0,"min":0,"max":90,"step":1,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"keyAngle","type":"number","defaultValue":45,"min":0,"max":90,"step":1,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"paperColor","type":"color","defaultValue":"#F5F5F0","visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"paperGrain","type":"number","defaultValue":0.15,"min":0,"max":0.5,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"registration","type":"number","defaultValue":0,"min":0,"max":5,"step":0.1,"visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"inkCyan","type":"color","defaultValue":"#00AEEF","visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"inkMagenta","type":"color","defaultValue":"#EC008C","visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"inkYellow","type":"color","defaultValue":"#FFF200","visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        {"key":"inkKey","type":"color","defaultValue":"#1a1a1a","visibleWhen":{"key":"colorMode","equals":"cmyk"}},
        ],
    },
    "image": {
        kind: "source",
        defaultName: "Image",
        params: [
        {"key":"fitMode","type":"select","defaultValue":"cover","options":["cover","contain"]},
        {"key":"scale","type":"number","defaultValue":1,"min":0.25,"max":4,"step":0.01},
        {"key":"offset","type":"vec2","defaultValue":[0,0],"min":-1,"max":1,"step":0.01},
        {"key":"svgRasterResolution","type":"select","defaultValue":"2048","options":["1024","2048","4096","8192"]},
        ],
    },
    "ink": {
        kind: "effect",
        defaultName: "Ink",
        params: [
        {"key":"blurPasses","type":"number","defaultValue":13,"min":1,"max":20,"step":1},
        {"key":"crispPasses","type":"number","defaultValue":3,"min":1,"max":6,"step":1},
        {"key":"crispBlend","type":"number","defaultValue":0.81,"min":0,"max":1,"step":0.01},
        {"key":"blurStrength","type":"number","defaultValue":0.044,"min":0.001,"max":0.08,"step":0.001},
        {"key":"blurDirection","type":"number","defaultValue":90,"min":-180,"max":180,"step":1},
        {"key":"dripLength","type":"number","defaultValue":1,"min":1,"max":10,"step":0.1},
        {"key":"dripWeight","type":"number","defaultValue":0.4,"min":0.2,"max":2,"step":0.1},
        {"key":"fluidNoise","type":"number","defaultValue":0.02,"min":0,"max":2,"step":0.01},
        {"key":"noiseScale","type":"number","defaultValue":1.2,"min":0.5,"max":8,"step":0.1},
        {"key":"smokeSpeed","type":"number","defaultValue":0.36,"min":0,"max":2,"step":0.01},
        {"key":"smokeTurbulence","type":"number","defaultValue":0,"min":0,"max":1.5,"step":0.01},
        {"key":"blurSpread","type":"number","defaultValue":1.6,"min":0.5,"max":4,"step":0.1},
        {"key":"colorMode","type":"select","defaultValue":"gradient","options":["gradient","source"]},
        {"key":"coreColor","type":"color","defaultValue":"#fffde8","visibleWhen":{"key":"colorMode","equals":"gradient"}},
        {"key":"midColor","type":"color","defaultValue":"#FFA700","visibleWhen":{"key":"colorMode","equals":"gradient"}},
        {"key":"edgeColor","type":"color","defaultValue":"#7192F1","visibleWhen":{"key":"colorMode","equals":"gradient"}},
        {"key":"backgroundColor","type":"color","defaultValue":"#000000"},
        {"key":"grainEnabled","type":"boolean","defaultValue":false},
        {"key":"grainIntensity","type":"number","defaultValue":0.3,"min":0,"max":0.3,"step":0.005},
        {"key":"grainScale","type":"number","defaultValue":1.5,"min":0.5,"max":5,"step":0.1},
        {"key":"bloomEnabled","type":"boolean","defaultValue":true},
        {"key":"bloomIntensity","type":"number","defaultValue":6.19,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0.97,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":0,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.96,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        ],
    },
    "live": {
        kind: "source",
        defaultName: "Live Camera",
        params: [
        {"key":"facingMode","type":"select","defaultValue":"user","options":["user","environment"]},
        {"key":"mirror","type":"boolean","defaultValue":true},
        {"key":"fitMode","type":"select","defaultValue":"cover","options":["cover","contain"]},
        {"key":"scale","type":"number","defaultValue":1,"min":0.25,"max":4,"step":0.01},
        {"key":"offset","type":"vec2","defaultValue":[0,0],"min":-1,"max":1,"step":0.01},
        ],
    },
    "magnify-lens": {
        kind: "source",
        defaultName: "Magnify Lens",
        params: [
        {"key":"radius","type":"number","defaultValue":0.18,"min":0.02,"max":0.5,"step":0.005},
        {"key":"softness","type":"number","defaultValue":0.4,"min":0,"max":1,"step":0.01},
        {"key":"zoom","type":"number","defaultValue":1.8,"min":1,"max":4,"step":0.05},
        {"key":"chromaStrength","type":"number","defaultValue":0.012,"min":0,"max":0.05,"step":0.001},
        {"key":"followLag","type":"number","defaultValue":0.2,"min":0,"max":0.95,"step":0.01},
        ],
    },
    "particle-grid": {
        kind: "effect",
        defaultName: "Particle Grid",
        params: [
        {"key":"gridResolution","type":"select","defaultValue":"256","options":["32","64","128","256","512","1024","2048","4096"]},
        {"key":"pointSize","type":"number","defaultValue":4,"min":1,"max":32,"step":1},
        {"key":"displacement","type":"number","defaultValue":0.1,"min":-2,"max":2,"step":0.01},
        {"key":"backgroundColor","type":"color","defaultValue":"#000000"},
        {"key":"noiseAmount","type":"number","defaultValue":0,"min":0,"max":2,"step":0.01},
        {"key":"noiseScale","type":"number","defaultValue":3,"min":0.5,"max":10,"step":0.1},
        {"key":"noiseSpeed","type":"number","defaultValue":0.5,"min":0,"max":3,"step":0.01},
        {"key":"bloomEnabled","type":"boolean","defaultValue":false},
        {"key":"bloomIntensity","type":"number","defaultValue":1.25,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":6,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        ],
    },
    "pattern": {
        kind: "effect",
        defaultName: "Pattern",
        params: [
        {"key":"cellSize","type":"number","defaultValue":12,"min":4,"max":48,"step":1},
        {"key":"preset","type":"select","defaultValue":"bars","options":["bars","candles","shapes"]},
        {"key":"colorMode","type":"select","defaultValue":"source","options":["source","quantized","monochrome","custom"]},
        {"key":"monoColor","type":"color","defaultValue":"#f5f5f0","visibleWhen":{"key":"colorMode","equals":"monochrome"}},
        {"key":"bgOpacity","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"source"}},
        {"key":"invert","type":"boolean","defaultValue":false},
        {"key":"customColorCount","type":"number","defaultValue":4,"min":2,"max":4,"step":1,"visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customLuminanceBias","type":"number","defaultValue":0,"min":-1,"max":1,"step":0.01,"visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customBgColor","type":"color","defaultValue":"#F5F5F0","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor1","type":"color","defaultValue":"#0d1014","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor2","type":"color","defaultValue":"#4d5057","visibleWhen":{"key":"colorMode","equals":"custom"}},
        {"key":"customColor3","type":"color","defaultValue":"#969aa2","visibleWhen":{"key":"customColorCount"}},
        {"key":"customColor4","type":"color","defaultValue":"#e1e2de","visibleWhen":{"key":"customColorCount"}},
        {"key":"bloomEnabled","type":"boolean","defaultValue":false},
        {"key":"bloomIntensity","type":"number","defaultValue":1.25,"min":0,"max":8,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomThreshold","type":"number","defaultValue":0.6,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomRadius","type":"number","defaultValue":6,"min":0,"max":24,"step":0.25,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        {"key":"bloomSoftness","type":"number","defaultValue":0.35,"min":0,"max":1,"step":0.01,"visibleWhen":{"key":"bloomEnabled","equals":true}},
        ],
    },
    "pixel-sorting": {
        kind: "effect",
        defaultName: "Pixel Sorting",
        params: [
        {"key":"threshold","type":"number","defaultValue":0.25,"min":0,"max":1,"step":0.01},
        {"key":"upperThreshold","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        {"key":"direction","type":"select","defaultValue":"horizontal","options":["horizontal","vertical"]},
        {"key":"mode","type":"select","defaultValue":"luma","options":["luma","hue","saturation"]},
        {"key":"reverse","type":"boolean","defaultValue":false},
        {"key":"range","type":"number","defaultValue":0.3,"min":0,"max":1,"step":0.01},
        ],
    },
    "pixel-trail": {
        kind: "source",
        defaultName: "Pixel Trail",
        params: [
        {"key":"cellSize","type":"number","defaultValue":24,"min":4,"max":128,"step":1},
        {"key":"radius","type":"number","defaultValue":0.04,"min":0.005,"max":0.3,"step":0.005},
        {"key":"decay","type":"number","defaultValue":0.9,"min":0.5,"max":0.999,"step":0.001},
        {"key":"displaceAmount","type":"number","defaultValue":0.02,"min":0,"max":0.2,"step":0.001},
        {"key":"intensity","type":"number","defaultValue":1,"min":0,"max":2,"step":0.05},
        ],
    },
    "pixelation": {
        kind: "effect",
        defaultName: "Pixelation",
        params: [
        {"key":"cellSize","type":"number","defaultValue":8,"min":2,"max":64,"step":1},
        {"key":"aspectRatio","type":"number","defaultValue":1,"min":0.25,"max":4,"step":0.05},
        ],
    },
    "plotter": {
        kind: "effect",
        defaultName: "Plotter",
        params: [
        {"key":"colorMode","type":"select","defaultValue":"ink","options":["ink","source"]},
        {"key":"gap","type":"number","defaultValue":12,"min":10,"max":120,"step":1},
        {"key":"weight","type":"number","defaultValue":1.5,"min":0.5,"max":5,"step":0.1},
        {"key":"angle","type":"number","defaultValue":90,"min":0,"max":180,"step":1},
        {"key":"crosshatch","type":"boolean","defaultValue":true},
        {"key":"crossAngle","type":"number","defaultValue":135,"min":0,"max":180,"step":1,"visibleWhen":{"key":"crosshatch","equals":true}},
        {"key":"threshold","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        {"key":"wobble","type":"number","defaultValue":0.3,"min":0,"max":1,"step":0.01},
        {"key":"paperColor","type":"color","defaultValue":"#f5f0e8"},
        {"key":"inkColor","type":"color","defaultValue":"#1a1a1a","visibleWhen":{"key":"colorMode","equals":"ink"}},
        ],
    },
    "posterize": {
        kind: "effect",
        defaultName: "Posterize",
        params: [
        {"key":"levels","type":"number","defaultValue":5,"min":2,"max":16,"step":1},
        {"key":"gamma","type":"number","defaultValue":1,"min":0.4,"max":2.5,"step":0.01},
        {"key":"mode","type":"select","defaultValue":"rgb","options":["rgb","luma"]},
        ],
    },
    "slice": {
        kind: "effect",
        defaultName: "Slice",
        params: [
        {"key":"amount","type":"number","defaultValue":180,"min":0,"max":480,"step":1},
        {"key":"sliceHeight","type":"number","defaultValue":28,"min":2,"max":240,"step":1},
        {"key":"blockWidth","type":"number","defaultValue":120,"min":8,"max":640,"step":1},
        {"key":"density","type":"number","defaultValue":0.58,"min":0,"max":1,"step":0.01},
        {"key":"dispersion","type":"number","defaultValue":0.18,"min":0,"max":0.5,"step":0.01},
        {"key":"speed","type":"number","defaultValue":0.2,"min":0,"max":2,"step":0.01},
        {"key":"direction","type":"select","defaultValue":"right","options":["right","left","both"]},
        ],
    },
    "smear": {
        kind: "effect",
        defaultName: "Progressive Blur",
        params: [
        {"key":"angle","type":"number","defaultValue":0,"min":0,"max":360,"step":1},
        {"key":"start","type":"number","defaultValue":0.25,"min":0,"max":1,"step":0.01},
        {"key":"end","type":"number","defaultValue":0.75,"min":0,"max":1,"step":0.01},
        {"key":"strength","type":"number","defaultValue":24,"min":0,"max":64,"step":1},
        {"key":"samples","type":"number","defaultValue":12,"min":4,"max":32,"step":1},
        ],
    },
    "text": {
        kind: "source",
        defaultName: "Text",
        params: [
        {"key":"text","type":"text","defaultValue":"basement.studio"},
        {"key":"anchor","type":"select","defaultValue":"center","options":["top-left","top-center","top-right","center-left","center","center-right","bottom-left","bottom-center","bottom-right"]},
        {"key":"offset","type":"vec2","defaultValue":[0,0],"min":-1,"max":1,"step":0.01},
        {"key":"fontSize","type":"number","defaultValue":48,"min":48,"max":600,"step":1},
        {"key":"fontFamily","type":"select","defaultValue":"sans","options":["display-serif","sans","mono","adhesion","blob","bsmnt-grotesque","bunker","caniche","carpenter","curia","ffflauta","numero","xer0","trovador","b-mecha","impact"]},
        {"key":"fontWeight","type":"number","defaultValue":700,"min":100,"max":900,"step":1},
        {"key":"letterSpacing","type":"number","defaultValue":-0.05,"min":-0.2,"max":0.3,"step":0.01},
        {"key":"textColor","type":"color","defaultValue":"#ffffff"},
        {"key":"backgroundColor","type":"color","defaultValue":"#000000"},
        {"key":"backgroundAlpha","type":"number","defaultValue":1,"min":0,"max":1,"step":0.01},
        ],
    },
    "threshold": {
        kind: "effect",
        defaultName: "Threshold",
        params: [
        {"key":"threshold","type":"number","defaultValue":0.5,"min":0,"max":1,"step":0.01},
        {"key":"softness","type":"number","defaultValue":0.02,"min":0,"max":0.2,"step":0.001},
        {"key":"noise","type":"number","defaultValue":0.08,"min":0,"max":0.3,"step":0.001},
        {"key":"invert","type":"boolean","defaultValue":false},
        ],
    },
    "video": {
        kind: "source",
        defaultName: "Video",
        params: [
        {"key":"fitMode","type":"select","defaultValue":"cover","options":["cover","contain"]},
        {"key":"scale","type":"number","defaultValue":1,"min":0.25,"max":4,"step":0.01},
        {"key":"offset","type":"vec2","defaultValue":[0,0],"min":-1,"max":1,"step":0.01},
        {"key":"playbackRate","type":"number","defaultValue":1,"min":0.25,"max":4,"step":0.05},
        ],
    },
    "voxel": {
        kind: "effect",
        defaultName: "Voxel",
        params: [
        {"key":"cellSize","type":"number","defaultValue":24,"min":4,"max":96,"step":1},
        {"key":"depth","type":"number","defaultValue":0,"min":0,"max":1,"step":0.01},
        {"key":"maxHeight","type":"number","defaultValue":6,"min":1,"max":8,"step":1,"visibleWhen":{"key":"depth"}},
        {"key":"topShade","type":"number","defaultValue":1,"min":0,"max":1.5,"step":0.01},
        {"key":"lightShade","type":"number","defaultValue":0.78,"min":0,"max":1.5,"step":0.01},
        {"key":"darkShade","type":"number","defaultValue":0.55,"min":0,"max":1.5,"step":0.01},
        {"key":"flipLight","type":"boolean","defaultValue":false},
        {"key":"lego","type":"boolean","defaultValue":false},
        {"key":"outlineWidth","type":"number","defaultValue":1,"min":0,"max":4,"step":0.1},
        {"key":"outlineColor","type":"color","defaultValue":"#0a0a0a"},
        ],
    },
};

// Default params for a freshly created layer of `type`, straight from the
// registry. Returns a fresh object each call — callers mutate it.
export function defaultParamsFor(type) {
    const def = LAYER_SCHEMA[type];
    if (!def) return {};
    const out = {};
    for (const param of def.params) out[param.key] = param.defaultValue;
    return out;
}

export function paramSchemaFor(type, key) {
    return LAYER_SCHEMA[type]?.params.find((p) => p.key === key) || null;
}
