#pragma once

#define IDD_THREEJS_RENDERER_PT        760
#define IDC_RENDERER_PT_SPF_EDIT       7601
#define IDC_RENDERER_PT_SPF_SPIN       7602
#define IDC_RENDERER_PT_GI_CLAMP_EDIT  7603
#define IDC_RENDERER_PT_GI_CLAMP_SPIN  7604
#define IDC_RENDERER_PT_FREEZE_SYNC    7605
#define IDC_RENDERER_USE_ORCHESTRATOR  7606
